language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    - jdk: openjdk9
    - jdk: oraclejdk9
    - jdk: openjdk10
    - jdk: oraclejdk10
    - jdk: openjdk11
    - os: osx
      osx_image: xcode9.2
      env: JAVA_HOME=$(/usr/libexec/java_home)
