language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13
    - os: osx
      osx_image: xcode9.2
      env: JAVA_HOME=$(/usr/libexec/java_home)

after_success:
  - mvn -B jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2